const keyboardLayoutEnglish = [
  [
    ['Backquote', '~', '`'],
    ['Digit1', '!', '1'],
    ['Digit2', '@', '2'],
    ['Digit3', '#', '3'],
    ['Digit4', '$', '4'],
    ['Digit5', '%', '5'],
    ['Digit6', '^', '6'],
    ['Digit7', '&', '7'],
    ['Digit8', '*', '8'],
    ['Digit9', '(', '9'],
    ['Digit0', ')', '0'],
    ['Minus', '_', '-'],
    ['Equal', '+', '='],
    ['Backspace', '&#x232b;'],
  ],
  [
    ['Tab', '&#x21e5;'],
    ['KeyQ', 'q'],
    ['KeyW', 'w'],
    ['KeyE', 'e'],
    ['KeyR', 'r'],
    ['KeyT', 't'],
    ['KeyY', 'y'],
    ['KeyU', 'u'],
    ['KeyI', 'i'],
    ['KeyO', 'o'],
    ['KeyP', 'p'],
    ['BracketLeft', '{', '['],
    ['BracketRight', '}', ']'],
    ['Backslash', '|', '\\'],
  ],
  [
    ['CapsLock', '&#x21ea;'],
    ['KeyA', 'a'],
    ['KeyS', 's'],
    ['KeyD', 'd'],
    ['KeyF', 'f'],
    ['KeyG', 'g'],
    ['KeyH', 'h'],
    ['KeyJ', 'j'],
    ['KeyK', 'k'],
    ['KeyL', 'l'],
    ['Semicolon', ':', ';'],
    ['Quote', '"', "'"],
    ['Enter', '&#x21a9;'],
  ],
  [
    ['ShiftLeft', '&#x21e7;'],
    ['IntlBackslash', '`', '~'],
    ['KeyZ', 'z'],
    ['KeyX', 'x'],
    ['KeyC', 'c'],
    ['KeyV', 'v'],
    ['KeyB', 'b'],
    ['KeyN', 'n'],
    ['KeyM', 'm'],
    ['Comma', '<', ','],
    ['Period', '>', '.'],
    ['Slash', '?', '/'],
    ['ShiftRight', '&#x21e7;'],
  ],
  [
    ['Fn', 'EN'],
    ['ControlLeft', '^', 'control'],
    ['AltLeft', '&#x2325;', 'option'],
    ['MetaLeft', '&#x2318;', 'command'],
    ['Space', ' '],
    ['MetaRight', '&#x2318;', 'command'],
    ['AltRight', '&#x2325;', 'option'],
    [['ArrowLeft', '&#x25C0;'], ['ArrowUp', '&#x25B2;'], ['ArrowDown', '&#x25BC;'], ['ArrowRight', '&#x25B6;']],
  ],
];

export default keyboardLayoutEnglish;
