const keyboardLayoutUkraine = [
  [
    ['Backquote', '/', '\\'],
    ['Digit1', '!', '1'],
    ['Digit2', '"', '2'],
    ['Digit3', '№', '3'],
    ['Digit4', ';', '4'],
    ['Digit5', '%', '5'],
    ['Digit6', ':', '6'],
    ['Digit7', '?', '7'],
    ['Digit8', '*', '8'],
    ['Digit9', '(', '9'],
    ['Digit0', ')', '0'],
    ['Minus', '_', '-'],
    ['Equal', '+', '='],
    ['Backspace', '&#x232b;'],
  ],
  [
    ['Tab', '&#x21e5;'],
    ['KeyQ', 'й'],
    ['KeyW', 'ц'],
    ['KeyE', 'у'],
    ['KeyR', 'к'],
    ['KeyT', 'е'],
    ['KeyY', 'н'],
    ['KeyU', 'г'],
    ['KeyI', 'ш'],
    ['KeyO', 'щ'],
    ['KeyP', 'з'],
    ['BracketLeft', 'Х', 'х'],
    ['BracketRight', 'Ї', 'ї'],
    ['Backslash', '₴', 'ʼ'],
  ],
  [
    ['CapsLock', '&#x21ea;'],
    ['KeyA', 'ф'],
    ['KeyS', 'і'],
    ['KeyD', 'в'],
    ['KeyF', 'а'],
    ['KeyG', 'п'],
    ['KeyH', 'р'],
    ['KeyJ', 'о'],
    ['KeyK', 'л'],
    ['KeyL', 'д'],
    ['Semicolon', 'Ж', 'ж'],
    ['Quote', 'Є', 'є'],
    ['Enter', '&#x21a9;'],
  ],
  [
    ['ShiftLeft', '&#x21e7;'],
    ['IntlBackslash', 'Ґ', 'ґ'],
    ['KeyZ', 'я'],
    ['KeyX', 'ч'],
    ['KeyC', 'с'],
    ['KeyV', 'м'],
    ['KeyB', 'и'],
    ['KeyN', 'т'],
    ['KeyM', 'ь'],
    ['Comma', 'Б', 'б'],
    ['Period', 'Ю', 'ю'],
    ['Slash', '.', ','],
    ['ShiftRight', '&#x21e7;'],
  ],
  [
    ['Fn', 'UA'],
    ['ControlLeft', '^', 'control'],
    ['AltLeft', '&#x2325;', 'option'],
    ['MetaLeft', '&#x2318;', 'command'],
    ['Space', ' '],
    ['MetaRight', '&#x2318;', 'command'],
    ['AltRight', '&#x2325;', 'option'],
    [['ArrowLeft', '&#x25C0;'], ['ArrowUp', '&#x25B2;'], ['ArrowDown', '&#x25BC;'], ['ArrowRight', '&#x25B6;']],
  ],
];

export default keyboardLayoutUkraine;
