const keyboardLayoutUkraine = [
  [
    '&#92;',
    ['!', '1'],
    ['"', '2'],
    ['№', '3'],
    [';', '4'],
    ['%', '5'],
    [':', '6'],
    ['?', '7'],
    ['*', '8'],
    ['(', '9'],
    [')', '0'],
    ['_', '-'],
    ['+', '='],
    'Backspace',
  ],
  [
    'Tab',
    'й',
    'ц',
    'у',
    'к',
    'е',
    'н',
    'г',
    'ш',
    'щ',
    'з',
    'х',
    'ї',
    ['ʼ', '₴'],
  ],
  ['CapsLock', 'ф', 'і', 'в', 'а', 'п', 'р', 'о', 'л', 'д', 'ж', 'є', 'Enter'],
  [
    'ShiftLeft',
    'ґ',
    'ч',
    'с',
    'м',
    'и',
    'т',
    'ь',
    'б',
    'ю',
    ',',
    '.',
    'ShiftRight',
  ],
  [
    'UA',
    ['^', 'Control'],
    ['&#x2325;', 'AltLeft'],
    ['&#x2318;', 'MetaLeft'],
    ' ',
    ['&#x2318;', 'MetaRight'],
    ['&#x2325;', 'AltRight'],
    ['ArrowLeft', 'ArrowUp', 'ArrowDown', 'ArrowRight'],
  ],
];

export default keyboardLayoutUkraine;
